### ISSUE TITLE
Remove Google+ contact info

### ISSUE THREAD

**Issue by davidsf** [opensouthcode/moraga#6]
**What is needed to do?**

In the conference contact page `contact/edit` there are input for Google+.

![Captura de pantalla de 2024-02-09 21-49-13](https://github.com/opensouthcode/moraga/assets/73978/543bae77-5fb4-4678-b622-56660b8009ff)

* Remove that input and the related code.
* Add a migration to remove that field `googleplus` in table `contacts`

**Comment by linuxonrails** [comment]
I am already working on it!
